"""
You will need the boxes:
* vEOS-4.15.2F - https://eos.arista.com/using-veos-with-vagrant-and-virtualbox/
* JunOS - juniper/ffp-12.1X47-D20.7-packetmode
   * To provision and test JunOS first you have to add the ssh vagrant ssh key into the ssh-agent. I.e.:
       ssh-add /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/keys/vagrant
"""

Vagrant.configure(2) do |config|
  config.vm.define "st2" do |st2|
    st2.vm.network "private_network", type: "dhcp"
    st2.vm.box = "puppetlabs/ubuntu-14.04-64-nocm"

    st2.vm.provider "virtualbox" do |v|
      v.memory = 1024
    end

    st2.vm.synced_folder "../", "/vagrant"

    st2.vm.provision "shell", inline: <<-SHELL
      sudo bash /vagrant/vagrant/st2/st2bootstrap-deb.sh
      export ETH0_IP=`ifconfig eth0 2>/dev/null|awk '/inet addr:/ {print $2}'|sed 's/addr://'`
      export ETH1_IP=`ifconfig eth1 2>/dev/null|awk '/inet addr:/ {print $2}'|sed 's/addr://'`
      sudo ln -sf /vagrant/packs/chatops_demo /opt/stackstorm/packs/chatops_demo
      sudo st2ctl reload
      # chmod 0600 /tmp/vagrant_key
      # ssh-agent -s
      # ssh-add /tmp/vagrant_key
      # sudo cp /tmp/rc.local /etc/rc.local
      sudo dd if=/dev/zero of=/swapfile bs=1024 count=524288
      sudo chmod 600 /swapfile
      sudo mkswap /swapfile
      sudo swapon /swapfile
      echo "Use the following URL to connect: https://$ETH1_IP"
    SHELL

  end
  config.vm.define "sw1" do |sw1|
    sw1.vm.box = "vEOS-lab-4.15.2.1F"

    sw1.vbguest.auto_update = false
    sw1.ssh.insert_key = false

    sw1.vm.network :forwarded_port, guest: 22, host: 12201, id: 'ssh'
    sw1.vm.network :forwarded_port, guest: 443, host: 12443, id: 'https'

    sw1.vm.network "private_network", virtualbox__intnet: "link_1", ip: "169.254.1.11", auto_config: false
    sw1.vm.network "private_network", virtualbox__intnet: "link_2", ip: "169.254.1.11", auto_config: false
  end
  config.vm.define "sw2" do |sw2|
    sw2.vm.box = "vEOS-lab-4.15.2.1F"

    sw2.vbguest.auto_update = false
    sw2.ssh.insert_key = false

    sw2.vm.network :forwarded_port, guest: 22, host: 12202, id: 'ssh'
    sw2.vm.network :forwarded_port, guest: 443, host: 12444, id: 'https'

    sw2.vm.network "private_network", virtualbox__intnet: "link_1", ip: "169.254.1.11", auto_config: false
    sw2.vm.network "private_network", virtualbox__intnet: "link_2", ip: "169.254.1.11", auto_config: false
  end
end
